import { FaLaptopCode } from "react-icons/fa";

export const projects = [
  {
    id: 1,
    title: "Aspire - Atmecs Technologies",
    description:
      "Was a part of their in-house IT team which was intended to build Aspire application. Created an organization module, talent module, HR admin module, resign employee module. UI implementation and API integration part was done.",
    technologies: ["React.js", "Node.js", "Bootstrap", "API Integration"],
    keyFeatures: [
      "Organization Module",
      "Talent Module",
      "HR Admin Module",
      "Resign Employee Module",
      "UI Implementation",
      "API Integration",
    ],
    duration: "29 Aug 2023 – 20 Feb 2025",
    position: "Senior Software Engineer",
    location: "Pune, India",
    employmentType: "Full Time",
    icon: <FaLaptopCode className="project-title-icon" />,
    github: "https://github.com",
    live: "https://example.com",
    image: "https://via.placeholder.com/600x400",
  },
  {
    id: 2,
    title: "Jio Signage - Xeedo Technologies",
    description:
      "Created user management portal with API integration for Jio signage. Implemented various forms and entirely converted existing signage system using React.js. Developed user authoring page with content management features.",
    technologies: ["React.js", "Material UI", "CSS", "API Integration"],
    keyFeatures: [
      "User Management Portal",
      "User Authoring Page",
      "Upload Content Functionality",
      "Create Content Module",
      "Playlist Creation",
      "Schedule Management",
    ],
    duration: "09 Dec 2022 – 30 June 2023",
    position: "Software Engineer",
    location: "Pune, India",
    employmentType: "Full Time",
    icon: <FaLaptopCode className="project-title-icon" />,
    github: "https://github.com",
    live: "https://example.com",
    image: "https://via.placeholder.com/600x400",
  },
  {
    id: 3,
    title: "Macy's - Zensar Technologies",
    description:
      "Returns Common Services (RCS/RCSS) is a suite of APIs that enables the enterprise to centralize all capabilities related to customer returns. This includes return policies, bypass policies, return initiation, return acceptance, return processing partners, estimated refund amounts, and return/problem declarations.",
    technologies: ["React.js", "Redux", "API Integration", "JavaScript"],
    keyFeatures: [
      "Returns Common Services (RCS/RCSS) API Suite",
      "Return Policies Management",
      "Bypass Policies Implementation",
      "Return Processing Partners Integration",
      "Enterprise Centralized Return Capabilities",
      "Estimated Refund Amounts Calculation",
    ],
    duration: "14 March 2022 – 1 Dec 2022",
    position: "Software Engineer",
    location: "Pune, India",
    employmentType: "Full Time",
    icon: <FaLaptopCode className="project-title-icon" />,
    github: "https://github.com",
    live: "https://example.com",
    image: "https://via.placeholder.com/600x400",
  },
  {
    id: 4,
    title: "IntelyForms - Oxcytech Technologies",
    description:
      "IntelyForms is a US-based no-code form building tool that allows users to easily build and configure forms and secure, integrated workflows to connect with their audience. Users can create workspaces, manipulate data, and integrate with various services.",
    technologies: [
      "React.js",
      "Redux",
      "API Integration",
      "JavaScript",
      "Material-UI",
    ],
    keyFeatures: [
      "Workspace Creation for Forms",
      "Form Management (Edit, Copy, View, Favorites, Delete)",
      "Mailchimp Integration",
      "Google Sheets Integration",
      "Google Calendar Integration",
      "Form Configuration & Customization",
      "Audience Connection Features",
    ],
    duration: "18 June 2020 – 28 Feb 2022",
    position: "UI Developer",
    location: "Pune, India",
    employmentType: "Full Time",
    icon: <FaLaptopCode className="project-title-icon" />,
    github: "https://github.com",
    live: "https://example.com",
    image: "https://via.placeholder.com/600x400",
  },
  {
    id: 5,
    title: "Inventory Management System - BroadStairs",
    description:
      "The Inventory Management System is a complete solution for managing inventory operations. It helps organizations manage their details, track sales, purchases, and inventory operations efficiently with comprehensive reporting capabilities.",
    technologies: ["React.js", "JavaScript", "CSS", "API Integration"],
    keyFeatures: [
      "User Management System",
      "Sales Tracking & Management",
      "Purchase Tracking & Management",
      "Inventory Operations Management",
      "Sales Report Generation",
      "Purchase Report Generation",
      "Inventory Report Generation",

      "Real-time Inventory Tracking",
    ],
    duration: "3 Jan 2019 – 17 Jun 2020",
    position: "Junior Ul Developer.",
    location: "Pune, India",
    employmentType: "Full Time",
    icon: <FaLaptopCode className="project-title-icon" />,
    github: "https://github.com",
    live: "https://example.com",
    image: "https://via.placeholder.com/600x400",
  },
  {
    id: 6,
    title: "Travels Automation System - SmartSoftware",
    description:
      "Automated Vehicle Tour System is a comprehensive vehicle service system that computerizes the arrangement and collection of recordings for travel distance, fuel resources management, and passenger tracking. The system streamlines tour operations and resource management.",
    technologies: ["React.js", "JavaScript", "CSS", "HTML5"],
    keyFeatures: [
      "Fuel Resources Management System",
      "Passenger Tracking & Counting",
      "Fuel Consumption Monitoring",
      "Tour Operations Streamlining",
      "Automated Recorded System",
    ],
    duration: "15 July 2017 – 31 Dec 2018",
    position: "UI Developer",
    location: "Pune, India",
    employmentType: "Full Time",
    icon: <FaLaptopCode className="project-title-icon" />,
    github: "https://github.com",
    live: "https://example.com",
    image: "https://via.placeholder.com/600x400",
  },
];
